### ISSUE TITLE
Differences from namshi/smtp image?

### ISSUE THREAD

**Issue by polarathene** [ix-ai/smtp#1]
There is credit given to the namshi/smtp dockerhub image, which this project seems to have forked from. No clear differences detailed though. Would it be possible to update that with a bit more information on what changes your image has?

**Comment by tlex** [comment]
Thanks for the question.

Initially, the difference was that this image was based on `debian:buster` instead of `debian:stretch`. This was implemented in the meanwhile by @namshi.

Right now, the only difference, that's not of cosmetic nature (read: the `entrypoint.sh` script has been changed to make [shellcheck](https://www.shellcheck.net/) happy), is the fact that the image, in addition to AMD64, is built for ARM64, ARMv7 and ARMv6.

Functionally there's no difference.

**Comment by polarathene** [comment]
Awesome, thanks for that! :)

Might be worth clarifying those differences on the DockerHub README, or other curious users might stumble upon here(I think I went to Gitlab via a badge on DockerHub, then the Gitlab issues linked to here, so that was a bit indirect).
