### ISSUE TITLE
Remote IP address

### ISSUE THREAD

**Issue by be4i** [ix-ai/smtp#20]
Hello,

exim uses the host local ip address as the client remote ip address

`250-******* Hello ***** [10.0.0.2]`

is it possible to show the real remote ip address?

**Comment by tlex** [comment]
This is a limitation due to the way you start the container. The only way to see the real IP address of the client is to have **no NAT** between the software and the client. Which means, among other things, the only chance you have is to start the container in [host network](https://docs.docker.com/network/host/) mode.

In short: your system, because of NAT, overwrites the "source IP" of the network package with the IP address of the router.

**Comment by be4i** [comment]
Thank you for the info and fast response!
