### ISSUE TITLE
retry time not reached for any host for 'mydomain.com'

### ISSUE THREAD

**Issue by JoeTN** [ix-ai/smtp#8]
I am trying to use your relay to relay mails to my Office 365 send connector.
When sending a email, I get the following error in the log, which I can't seem to solve:

292 delivering 1mqjmk-00004h-Q0
292 R: smarthost for mymail@mydomain.com
293 T: remote_smtp_smarthost for mymail@mydomain.com
292 LOG: retry_defer MAIN
292   == mymail@mydomain.com R=smarthost T=remote_smtp_smarthost defer (-53): retry time not reached for any host for 'mydomain.com'

This is my Docker compose file: https://pastebin.com/aKDJxNcQ

I am using your relay to send mails through my Office 365 connector which works just fine when tested on it's own.

I hope you have an idea for a solution.

Regards :-)

**Comment by tlex** [comment]
Oh wow, this issue has been opened for long.

Does the problem still persist? Unfortunately, I have no way of testing O365. However the problem seems network-related (does the started docker container have access to connect to the relay?).

I'm closing the issue. Please let me know if you think there's anything I can do on the ix-ai/smtp side.

**Comment by JoeTN** [comment]
Better late than never ;-)
I solved the problem. As far as I remember, I forgot to include my subnet as an allowed sender.
